# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-profile_photo']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profile_photo',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pub_date_created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.CharField(blank=True, default='contact', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='bio', max_length=100),
        ),
    ]
