# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0002_auto_20190529_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=80),
        ),
    ]
